services:
  redis:
    image: "redis"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly yes"]
  postgres:
    image: "postgres"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_DB=tiw
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - redis
    env_file:
      - ./server/.env
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - server
    env_file:
      - ./client/.env
volumes:
  postgres:
  redis:
